# Generated by Django 6.0.3 on 2026-03-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Número de Serie (VIN)')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('EN_TALLER', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=15)),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador General'), ('MECANICO', 'Soporte / Mecánico'), ('CHOFER', 'Chofer')], default='CHOFER', max_length=15)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo (Afinación, Aceite)'), ('CORRECTIVO', 'Correctivo (Falla mecánica)')], max_length=15)),
                ('fecha_servicio', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(max_length=100)),
                ('descripcion_trabajo', models.TextField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('fecha_regreso', models.DateTimeField(blank=True, null=True)),
                ('km_salida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_regreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_vehicular.vehiculo')),
            ],
        ),
    ]
