# Generated by Django 6.0.3 on 2026-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_vehicular", "0002_polizaseguro"),
    ]

    operations = [
        migrations.AddField(
            model_name="mantenimiento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROCESO", "En Proceso"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
