# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0005_chofer_foto_chofer_tipo_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=10),
        ),
    ]
