# Generated by Django 6.0.3 on 2026-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_vehicular", "0006_chofer_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="mantenimiento",
            name="fecha_regreso",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Regreso (Estimada o Real)"
            ),
        ),
    ]
