# Generated by Django 6.0.3 on 2026-04-09 03:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_vehicular', '0007_mantenimiento_fecha_regreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fecha_salida'], 'verbose_name': 'Asignación de Viaje', 'verbose_name_plural': 'Bitácora de Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={'ordering': ['apellidos', 'nombre'], 'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_servicio'], 'verbose_name': 'Registro de Mantenimiento', 'verbose_name_plural': 'Historial de Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='polizaseguro',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Póliza de Seguro', 'verbose_name_plural': 'Pólizas de Seguros'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.chofer', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa (En Ruta)'), ('FINALIZADA', 'Finalizada (Devuelto)')], default='ACTIVA', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=10, verbose_name='Estado Laboral'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='choferes/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 números, sin espacios ni ladas internacionales.', regex='^\\d{10}$')], verbose_name='Teléfono (10 dígitos)'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='tipo_licencia',
            field=models.CharField(choices=[('A', 'Tipo A (Particulares)'), ('B', 'Tipo B (Mercantil/Transporte)'), ('C', 'Tipo C (Carga)')], default='A', max_length=2, verbose_name='Tipo de Licencia'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion_trabajo',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Regreso Estimada'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_servicio',
            field=models.DateField(verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='taller',
            field=models.CharField(max_length=100, verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo (Afinación, Aceite)'), ('CORRECTIVO', 'Correctivo (Falla mecánica)'), ('ESTETICO', 'Estético (Hojalatería, Lavado)')], max_length=15, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Licencia'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='vencimiento_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de Licencia'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='aseguradora',
            field=models.CharField(choices=[('QUALITAS', 'Quálitas'), ('GNP', 'GNP Seguros'), ('HDI', 'HDI Seguros'), ('MAPFRE', 'MAPFRE'), ('AXA', 'AXA Seguros'), ('INBURSA', 'Inbursa'), ('ZURICH', 'Zurich'), ('OTRA', 'Otra')], max_length=50, verbose_name='Aseguradora'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='numero_poliza',
            field=models.CharField(max_length=50, verbose_name='No. Póliza'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control_vehicular.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En Ruta'), ('EN_TALLER', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=15, verbose_name='Estado Operativo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kilometraje Actual'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('CHEVROLET', 'Chevrolet'), ('NISSAN', 'Nissan'), ('TOYOTA', 'Toyota'), ('FORD', 'Ford'), ('VOLKSWAGEN', 'Volkswagen'), ('HONDA', 'Honda'), ('KIA', 'Kia'), ('MAZDA', 'Mazda'), ('HYUNDAI', 'Hyundai'), ('OTRA', 'Otra (Especificar en modelo)')], default='NISSAN', max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placas',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Usa solo mayúsculas, números y guiones (Ej. UMK-123-A).', regex='^[A-Z0-9\\-]{6,10}$')], verbose_name='Placas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='El VIN debe tener 17 caracteres alfanuméricos. No se permiten las letras I, O, ni Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='Número de Serie (VIN)'),
        ),
    ]
